# fly.toml app configuration file generated for educationbitlab on 2023-04-19T22:11:53+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "educationbitlab"
primary_region = "arn"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
